RECIPE_START_TOKEN = "[START]"
RECIPE_END_TOKEN = "[END]"

TITLE_START_TOKEN = "[TITLE_START]"
TITLE_END_TOKEN = "[TITLE_END]"

NER_NEXT_TOKEN = "[NER_NEXT]"

INGREDIENTS_START_TOKEN = "[INGREDIENTS_START]"
INGREDIENTS_END_TOKEN = "[INGREDIENTS_END]"
INGREDIENTS_NEXT_TOKEN = "[INGREDIENTS_NEXT]"

INSTRUCTIONS_START_TOKEN = "[INSTRUCTIONS_START]"
INSTRUCTIONS_END_TOKEN = "[INSTRUCTIONS_END]"
INSTRUCTIONS_NEXT_TOKEN = "[INSTRUCTIONS_NEXT]"

NEW_TOKENS = [
    RECIPE_START_TOKEN,
    RECIPE_END_TOKEN,
    TITLE_START_TOKEN,
    TITLE_END_TOKEN,
    NER_NEXT_TOKEN,
    INGREDIENTS_START_TOKEN,
    INGREDIENTS_END_TOKEN,
    INGREDIENTS_NEXT_TOKEN,
    INSTRUCTIONS_START_TOKEN,
    INSTRUCTIONS_END_TOKEN,
    INSTRUCTIONS_NEXT_TOKEN,
]
